Initial solution
Resci/HW-03 pull request #6
Opened 2021-01-20 12:15 UTC by Resci

2021-01-20 12:44 UTC, Vedroid requested changes

2021-01-20 12:44 UTC, Vedroid commented on src/main/webapp/WEB-INF/views/cars/add.jsp
> +            <input type="text" name="manufacturer_id" form="car">
What happens if I enter "asdwq"

2021-01-20 12:44 UTC, Vedroid commented on src/main/webapp/WEB-INF/views/cars/add_driver_to_car.jsp
> +            <input type="text" name="driver_id" form="car">
What happens if I enter name instead of id
or I will not enter anything

2021-01-20 12:44 UTC, Vedroid commented on src/main/webapp/web.xml
> +        <url-pattern>/cars/add_driver_to_car</url-pattern>
Bad URLs naming
[checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/08_servlets_practice_checklist.html)

2021-01-20 12:44 UTC, Vedroid commented on src/main/java/com/mate/controller/car/AddCarController.java
> +                        Long.parseLong(req.getParameter("manufacturer_id")))));
What if the specified id is not in the database

2021-01-20 12:44 UTC, Vedroid commented on src/main/java/com/mate/controller/car/AddDriverToCarController.java
> +                carService.get(Long.parseLong(req.getParameter("car_id"))));
What if the specified id is not in the database

2021-01-20 13:16 UTC, Resci commented on src/main/webapp/WEB-INF/views/cars/add.jsp
> +            <input type="text" name="manufacturer_id" form="car">
I forget to push this commit

2021-01-20 17:25 UTC, Vedroid approved these changes

2021-01-21 09:09 UTC, KseniiaMakarova requested changes

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/IndexController.java
> +        }
let's remove this please

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +</table>
let's remove this and use the following:
`<a href="${pageContext.request.contextPath}/drivers/create">Create New Driver</a><br>`
`<a href="${pageContext.request.contextPath}/drivers/">Display All Drivers</a><br>`

and so on

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/car/AddCarController.java
> +        } catch (NoSuchElementException e) {
it is bad practice catching RuntimeExceptions

let's remove try-catch and assume that we will not receive the wrong id

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/car/AddDriverToCarController.java
> +        } catch (NoSuchElementException e) {
same here

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/car/DeleteCarController.java
> +        carService.delete(Long.parseLong(req.getParameter("delete")));
```suggestion
        carService.delete(Long.parseLong(req.getParameter("id")));
```

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/driver/AddDriverController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/add.jsp").forward(req, resp);
let's use send redirect here

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/driver/DeleteDriverController.java
> +        driverService.delete(Long.parseLong(req.getParameter("delete")));
```suggestion
        driverService.delete(Long.parseLong(req.getParameter("id")));
```

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/manufacturer/AddManufacturerController.java
> +        req.getRequestDispatcher("/WEB-INF/views/manufacturers/add.jsp").forward(req, resp);
use sendRedirect

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/manufacturer/DeleteManufacturerController.java
> +        manufacturerService.delete(Long.parseLong(req.getParameter("delete")));
```suggestion
        manufacturerService.delete(Long.parseLong(req.getParameter("id")));
```

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/cars/add.jsp
> +<form method="post" id="car"></form>
where is the action that we will do when we press the Submit button?

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/cars/drivers/add.jsp
> +<form method="post" id="car"></form>
same

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/drivers/add.jsp
> +<form method="post" id="driver"></form>
same

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/manufacturers/add.jsp
> +<form method="post" id="manufacturer"></form>
same

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/css/table_dark.css
> +}
add empty line

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/java/com/mate/controller/driver/DeleteDriverController.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp)
```suggestion
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
```
in all DeleteControllers make this method `doGet()`

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/drivers/all.jsp
> +                </form>
```suggestion
                <a href="${pageContext.request.contextPath}/drivers/delete?id=${driver.id}">DELETE</a>
```
same for car and manufacturer

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/drivers/all</url-pattern>
```suggestion
        <url-pattern>/drivers/</url-pattern>
```

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/cars/all</url-pattern>
```suggestion
        <url-pattern>/cars/</url-pattern>
```

2021-01-21 09:09 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturers/all</url-pattern>
```suggestion
        <url-pattern>/manufacturers/</url-pattern>
```

2021-01-21 16:08 UTC, KseniiaMakarova approved these changes

2021-01-21 16:08 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/drivers/add.jsp
> +    <title>All drivers</title>
```suggestion
    <title>Add driver</title>
```

2021-01-21 16:08 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +<form method="post" id="redirect"></form>
let's remove this

2021-01-25 07:17 UTC, merged