Hw 09
Resci/HW-03 pull request #9
Opened 2021-01-25 07:43 UTC by Resci

2021-01-25 07:45 UTC, grom4er approved these changes

2021-01-25 16:56 UTC, Sofasmile requested changes

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/dao/jdbcimpl/DriverDaoJdbcImpl.java
> +        if (driverId == null) {
do we need this checking? Can we get null id from db?

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/dao/jdbcimpl/DriverDaoJdbcImpl.java
> +        String selectQuery = "SELECT * FROM drivers where login LIKE ? and deleted = false";
better don't use LIKE with login

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/model/Driver.java
> +    private String password;
we should add login and password to equals and hashcode

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/security/AuthenticationServiceImpl.java
> +    private static final Injector injector = Injector.getInstance("com.mate");
do we need injector here? let's use Inject annotation instead

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/security/AuthenticationServiceImpl.java
> +        Driver driver = driverService.findByLogin(login).orElseThrow(
Read about it in the Slack)

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/web/filter/AuthenticationFilter.java
> +        if (url.equals("/drivers/add") || url.equals("/drivers/login")) {
Read about it in the Slack)

2021-01-25 16:56 UTC, Sofasmile commented on src/main/java/com/mate/web/filter/AuthenticationFilter.java
> +        if (driverService.get(driverId) == null) {
https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/09_filters_checklist.html
- 5 paragraph

2021-01-26 07:54 UTC, Sofasmile requested changes

2021-01-26 07:54 UTC, Sofasmile commented on src/main/java/com/mate/web/filter/AuthenticationFilter.java
> +            driverService.get(driverId);
не варто тут відловлювати NoSuchElementException. Давай просто перевіряти чи driverId == null і робити:
response.sendRedirect("/drivers/login");
return;

2021-01-26 09:16 UTC, Sofasmile requested changes

2021-01-26 09:16 UTC, Sofasmile commented on src/main/java/com/mate/web/filter/AuthenticationFilter.java
> +    private final DriverService driverService = (DriverService) injector
do we need these fields?

2021-01-26 09:17 UTC, Sofasmile commented
travis failed

2021-01-26 09:26 UTC, Resci commented
> travis failed

Forget push commit

2021-01-26 09:48 UTC, Sofasmile approved these changes

2021-01-26 11:23 UTC, merged